name: ChunkOwn
main: com.codisimus.plugins.chunkown.ChunkOwn
version: 1.0.1
author: Codisimus
website: www.codisimus.com
description: Simple area protection based on Chunks
load: POSTWORLD
softdepend: [Vault]
commands:
  co:
    description: Displays the ChunkOwn help page
    usage: /<command> help
    aliases: [chunk, chunkown]
permissions:
  chunkown.buy:
    description: Needed to purchase Chunks (/chunk buy)
    default: true
  chunkown.autobuy:
    description: Needed to buy Chunks by placing a Block
  chunkown.addon.blockpvp:
    description: Needed to buy the BlockPvP Add-on (/buy blockpvp)
  chunkown.addon.blockpve:
    description: Needed to buy the BlockPvE Add-on (/buy blockpve)
  chunkown.addon.blockexplosions:
    description: Needed to buy the BlockExplosions Add-on (/buy blockexplosions)
  chunkown.addon.lockchests:
    description: Needed to buy the LockChests Add-on (/buy lockchests)
  chunkown.addon.lockdoors:
    description: Needed to buy the LockDoors Add-on (/buy lockdoors)
  chunkown.addon.disablebuttons:
    description: Needed to buy the DisableButtons Add-on (/buy disablebuttons)
  chunkown.addon.disablepistons:
    description: Needed to buy the DisablePistons Add-on (/buy disablepistons)
  chunkown.addon.alarm:
    description: Needed to buy the Alarm Add-on (/buy alarm)
  chunkown.addon.heal:
    description: Needed to buy the Heal Add-on (/buy heal)
  chunkown.addon.feed:
    description: Needed to buy the Feed Add-on (/buy feed)
  chunkown.addon.notify:
    description: Needed to buy the Notify Add-on (/buy notify)
  chunkown.addon.noautodisown:
    description: Needed to buy the NoAutoDisown Add-on (/buy noautodisown)
  chunkown.preview:
    description: Needed to preview the boundaries of Chunks (/chunk preview)
    default: true
  chunkown.info:
    description: Needed to see who the owner and CoOwners are of the current Chunk (/chunk info)
  chunkown.coowner:
    description: Needed to add a CoOwner to your Chunk (/chunk coowner)
    default: true
  chunkown.ninja:
    description: You will not trigger alarms when stepping on others property
  chunkown.free:
    description: Own Chunks free of charge
  chunkown.admin:
    description: Edit other Players' Chunks
  chunkown.mustowntobuild:
    description: Restricts Players from building anywhere they don't own that is above the OwnLowerLimit level
  chunkown.limit.-1:
    description: limit the number of Chunks a player can own. -1 = unlimited. -1 can be changed to any number 0 - 100. Largest number is taken if player has more than 1 node (-1 is considered larger than 100)
  chunkown.limit.0:
    description: limit the number of Chunks a player can own. -1 = unlimited. -1 can be changed to any number 0 - 100. Largest number is taken if player has more than 1 node (-1 is considered larger than 100)
  chunkown.limit.1:
    description: limit the number of Chunks a player can own. -1 = unlimited. -1 can be changed to any number 0 - 100. Largest number is taken if player has more than 1 node (-1 is considered larger than 100)
  chunkown.limit.2:
    description: limit the number of Chunks a player can own. -1 = unlimited. -1 can be changed to any number 0 - 100. Largest number is taken if player has more than 1 node (-1 is considered larger than 100)
  chunkown.limit.3:
    description: limit the number of Chunks a player can own. -1 = unlimited. -1 can be changed to any number 0 - 100. Largest number is taken if player has more than 1 node (-1 is considered larger than 100)
  chunkown.limit.4:
    description: limit the number of Chunks a player can own. -1 = unlimited. -1 can be changed to any number 0 - 100. Largest number is taken if player has more than 1 node (-1 is considered larger than 100)
  chunkown.limit.5:
    description: limit the number of Chunks a player can own. -1 = unlimited. -1 can be changed to any number 0 - 100. Largest number is taken if player has more than 1 node (-1 is considered larger than 100)
  chunkown.limit.10:
    description: limit the number of Chunks a player can own. -1 = unlimited. -1 can be changed to any number 0 - 100. Largest number is taken if player has more than 1 node (-1 is considered larger than 100)
  chunkown.limit.20:
    description: limit the number of Chunks a player can own. -1 = unlimited. -1 can be changed to any number 0 - 100. Largest number is taken if player has more than 1 node (-1 is considered larger than 100)
  chunkown.limit.50:
    description: limit the number of Chunks a player can own. -1 = unlimited. -1 can be changed to any number 0 - 100. Largest number is taken if player has more than 1 node (-1 is considered larger than 100)
  chunkown.limit.100:
    description: limit the number of Chunks a player can own. -1 = unlimited. -1 can be changed to any number 0 - 100. Largest number is taken if player has more than 1 node (-1 is considered larger than 100)