name: ChunkOwn
main: com.codisimus.plugins.chunkown.ChunkOwn
version: 0.7.0 dev
author: Codisimus
website: www.codisimus.com
description: Simple area protection based on Chunks
startup: postworld
depend: [Vault]
commands:
  chunk:
    description: Used to own the current Chunk that you are in
    usage: /<command> help
permissions:
  chunkown.own:
    default: true
    description: Needed to manage owned Chunks (/chunk buy, /chunk sell, /chunk list, /chunk clear)
  chunkown.addon.blockpvp:
    default: true
    description: Needed to buy the BlockPvP Add-on (/buy blockpvp)
  chunkown.addon.blockpve:
    default: false
    description: Needed to buy the BlockPvE Add-on (/buy blockpve)
  chunkown.addon.blockexplosions:
    default: true
    description: Needed to buy the BlockExplosions Add-on (/buy blockexplosions)
  chunkown.addon.lockchests:
    default: true
    description: Needed to buy the LockChests Add-on (/buy lockchests)
  chunkown.addon.lockdoors:
    default: true
    description: Needed to buy the LockDoors Add-on (/buy lockdoors)
  chunkown.addon.disablebuttons:
    default: true
    description: Needed to buy the DisableButtons Add-on (/buy disablebuttons)
  chunkown.addon.disablepistons:
    default: true
    description: Needed to buy the DisablePistons Add-on (/buy disablepistons)
  chunkown.addon.alarm:
    default: false
    description: Needed to buy the Alarm Add-on (/buy alarm)
  chunkown.addon.heal:
    default: false
    description: Needed to buy the Heal Add-on (/buy heal)
  chunkown.addon.feed:
    default: false
    description: Needed to buy the Feed Add-on (/buy feed)
  chunkown.addon.notify:
    default: true
    description: Needed to buy the Notify Add-on (/buy notify)
  chunkown.preview:
    default: true
    description: Needed to preview the boundaries of Chunks (/chunk preview)
  chunkown.info:
    default: true
    description: Needed to see who the owner and CoOwners are of the current Chunk (/chunk info)
  chunkown.coowner:
    default: true
    description: Needed to add a CoOwner to your Chunk (/chunk coowner)
  chunkown.free:
    default: op
    description: Own Chunks free of charge
  chunkown.admin:
    default: op
    description: Edit other Players' Chunks
  chunkown.mustowntobuild:
    default: false
    description: Restricts Players from building anywhere they don't own that is above the OwnLowerLimit level
  chunkown.limit.-1:
    default: true
    description: limit the number of Chunks a player can own. -1 = unlimited. -1 can be changed to any number 0 - 100. Largest number is taken if player has more than 1 node (-1 is considered larger than 100)
  chunkown.limit.0:
    default: true
    description: limit the number of Chunks a player can own. -1 = unlimited. -1 can be changed to any number 0 - 100. Largest number is taken if player has more than 1 node (-1 is considered larger than 100)
  chunkown.limit.1:
    default: true
    description: limit the number of Chunks a player can own. -1 = unlimited. -1 can be changed to any number 0 - 100. Largest number is taken if player has more than 1 node (-1 is considered larger than 100)
  chunkown.limit.2:
    default: true
    description: limit the number of Chunks a player can own. -1 = unlimited. -1 can be changed to any number 0 - 100. Largest number is taken if player has more than 1 node (-1 is considered larger than 100)
  chunkown.limit.3:
    default: true
    description: limit the number of Chunks a player can own. -1 = unlimited. -1 can be changed to any number 0 - 100. Largest number is taken if player has more than 1 node (-1 is considered larger than 100)
  chunkown.limit.4:
    default: true
    description: limit the number of Chunks a player can own. -1 = unlimited. -1 can be changed to any number 0 - 100. Largest number is taken if player has more than 1 node (-1 is considered larger than 100)
  chunkown.limit.5:
    default: true
    description: limit the number of Chunks a player can own. -1 = unlimited. -1 can be changed to any number 0 - 100. Largest number is taken if player has more than 1 node (-1 is considered larger than 100)
  chunkown.limit.10:
    default: true
    description: limit the number of Chunks a player can own. -1 = unlimited. -1 can be changed to any number 0 - 100. Largest number is taken if player has more than 1 node (-1 is considered larger than 100)
  chunkown.limit.20:
    default: true
    description: limit the number of Chunks a player can own. -1 = unlimited. -1 can be changed to any number 0 - 100. Largest number is taken if player has more than 1 node (-1 is considered larger than 100)
  chunkown.limit.50:
    default: true
    description: limit the number of Chunks a player can own. -1 = unlimited. -1 can be changed to any number 0 - 100. Largest number is taken if player has more than 1 node (-1 is considered larger than 100)
  chunkown.limit.100:
    default: true
    description: limit the number of Chunks a player can own. -1 = unlimited. -1 can be changed to any number 0 - 100. Largest number is taken if player has more than 1 node (-1 is considered larger than 100)